# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KoreanGuardians' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Moya', '~> 13.0'
pod 'SwiftyJSON'
pod 'Kingfisher'
pod 'SwiftLint'
pod 'SwiftGifOrigin', '~> 1.6.1'

  # Pods for KoreanGuardians

end
